'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
type Decision = {recordId:string;recordDigest:string;state:string;content:{summary:string;anchor:{startMs:number}}};
type Source = {sourceId:string;token:string|null;metadata:{durationMs:number;mediaType:string};decisions:Decision[]};
type Result = {pendingDecisions?:{token:string;key:string}[];ok:boolean;reason?:string;sessionId?:string;home?:{agent:{currentVersionId:string};recentSessions:{sessionId:string;sourceMode:string;terminal:boolean;agent:{baseVersionId:string}}[]};sources?:Source[];image?:string;failedDrafts?:{token:string;reason:string}[]};
type Bridge = {trainingLocal:(operation:string,args:unknown)=>Promise<Result>};
const bridge = () => (window as unknown as {implexaDesktop?:Bridge}).implexaDesktop;
export default function TrainingSource({slug}:{slug:string}) {
 const [retention] = useState(()=>{const d=new Date();d.setUTCFullYear(d.getUTCFullYear()+1);d.setUTCMilliseconds(0);return d.toISOString();});
 const [session,setSession]=useState(''); const [sources,setSources]=useState<Source[]>([]); const [selected,setSelected]=useState<Source|null>(null);
 const [busy,setBusy]=useState(''); const [error,setError]=useState(''); const [consent,setConsent]=useState(false); const [image,setImage]=useState('');
 const [time,setTime]=useState(0); const [relation,setRelation]=useState('accepted'); const [property,setProperty]=useState('motion_rhythm');
 const [chosen,setChosen]=useState('');const [why,setWhy]=useState('');const [process,setProcess]=useState('');const [behavior,setBehavior]=useState('');
 const [pending,setPending]=useState<{token:string;key:string}[]>([]);
 const [failed,setFailed]=useState<{token:string;reason:string}[]>([]);const [sessionKey]=useState(()=>crypto.randomUUID()); const [decisionKey,setDecisionKey]=useState(()=>crypto.randomUUID());
 async function call(operation:string,args:unknown) {const b=bridge(); if(!b?.trainingLocal) throw new Error('Open this page in an updated Implexa Desktop to select a local training source.');const r=await b.trainingLocal(operation,args);if(!r.ok)throw new Error(r.reason||'Training is unavailable. Your draft is preserved.');return r;}
 async function load(id:string){const r=await call('list',{sessionId:id});setSources(r.sources||[]);setFailed(r.failedDrafts||[]);setPending(r.pendingDecisions||[]);}
 async function work(label:string,fn:()=>Promise<void>){setBusy(label);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Training is unavailable.');}finally{setBusy('');}}
 useEffect(()=>{void work('Loading training evidence',async()=>{const r=await call('home',{slug});const prior=r.home?.recentSessions.find(s=>s.sourceMode==='raw_input'&&!s.terminal&&s.agent.baseVersionId===r.home?.agent.currentVersionId);if(prior){setSession(prior.sessionId);await load(prior.sessionId);}});},[slug]);
 async function add(){await work('Verifying the selected source and saving its identity',async()=>{let id=session;if(!id){const r=await call('create',{slug,key:sessionKey});id=r.sessionId!;setSession(id);}await call('select',{sessionId:id,consent:{localCustody:true,boundedEvidence:true,futureSelection:true}});await load(id);});}
 async function preview(){if(selected?.token) await work('Verifying and extracting this frame',async()=>{const r=await call('preview',{token:selected.token,timeMs:time});setImage(r.image||'');});}
 async function annotate(){if(!selected?.token)return;await work('Saving the visual decision draft',async()=>{await call('annotate',{token:selected.token,timeMs:time,idempotencyKey:decisionKey,decision:{chosen,why,process,desiredBehavior:behavior},content:{relation,properties:[property],mustNotCopy:['source text','source logos','protected identity'],applicability:{taskFacts:[],stages:['preview','build','qa'],exceptions:[],priority:50},governance:{rightsBasis:'owner_created',rightsReceipt:'Coach confirms ownership and grants bounded evidence use',disclosure:'owner_private',retentionUntil:retention,deletionPolicy:'revoke_then_delete_derivatives',consent:true,attribution:''}}});setDecisionKey(crypto.randomUUID());await load(session);});}
 return <main className="mx-auto max-w-3xl px-6 py-12 space-y-6"><Link href="/training">← Training</Link><h1 className="text-2xl font-semibold">Train {slug}</h1>
 <p>Teach visual decisions from your own video or image without starting a run. Accepted decisions are eligible for this agent version’s future Manager selections.</p>
 <label className="flex gap-3"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>I created this source and consent to local custody, saving bounded frame evidence, and relevant future evidence selection. The original stays on this computer.</label>
 <button className="btn-primary" disabled={!consent||!!busy} onClick={add}>Add training source</button>
 {busy&&<p role="status">{busy}… Large files can take several minutes.</p>}{error&&<p role="alert">{error.replaceAll('_',' ')}</p>}
 {failed.map(d=><div key={d.token}><p>Preserved draft: {d.reason.replaceAll('_',' ')}</p><button disabled={!!busy} onClick={()=>work('Retrying registration',async()=>{await call('register',{token:d.token});await load(session);})}>Retry registration</button></div>)}
 {pending.map(d=><p key={d.key}>Preserved decision awaiting registration. <button disabled={!!busy} onClick={()=>work('Retrying saved decision',async()=>{await call('retryDraft',d);await load(session);})}>Retry saved decision</button></p>)}
 {sources.map((s,index)=><section key={s.sourceId} className="rounded border border-ink-700 p-4 space-y-3"><h2>Source {index+1} · Owner demonstration · {s.metadata.mediaType}</h2><button disabled={!s.token||!!busy} onClick={()=>{setSelected(s);setTime(0);setImage('');}}>Review source</button>{!s.token&&<p>Local evidence is on another computer or unavailable.</p>}
 <ul>{s.decisions.map(d=><li key={d.recordId} className="py-3"><p>{(d.content.anchor.startMs/1000).toFixed(2)}s · {d.state}</p><p>{d.content.summary}</p>{d.state==='draft'&&<button disabled={!!busy||!s.token} onClick={()=>work('Revalidating source and accepting decision',async()=>{await call('accept',{token:s.token,recordId:d.recordId});await load(session);})}>Accept decision for future selection</button>}</li>)}</ul></section>)}
 {selected&&<section className="rounded border border-ink-700 p-4 space-y-4"><h2>Timestamped visual decision</h2><label className="block">Frame time: {(time/1000).toFixed(2)} seconds<input className="block w-full" type="range" min="0" max={Math.max(0,selected.metadata.durationMs-1)} step="1" value={time} onChange={e=>{setTime(Number(e.target.value));setImage('');setDecisionKey(crypto.randomUUID());}}/></label><button disabled={!!busy} onClick={preview}>Preview this frame</button>{image&&<img src={image} alt={`Training source frame at ${time/1000} seconds`} className="w-full"/>}
 <label className="block">Evidence relation <select value={relation} onChange={e=>{setRelation(e.target.value);setDecisionKey(crypto.randomUUID());}}><option value="accepted">Positive example</option><option value="rejected">Negative example</option><option value="contrast">Contrastive example</option></select></label>
 <label className="block">Visual property <select value={property} onChange={e=>{setProperty(e.target.value);setDecisionKey(crypto.randomUUID());}}>{['motion_rhythm','layout_variety','information_hierarchy','typography_treatment','transition_quality','animation_continuity','composition_density'].map(p=><option key={p} value={p}>{p.replaceAll('_',' ')}</option>)}</select></label>
 {([['What was chosen',chosen,setChosen],['Why this choice',why,setWhy],['Tool or process used',process,setProcess],['Desired visual, motion or layout behavior',behavior,setBehavior]] as const).map(([label,value,set])=><label className="block" key={label}>{label}<textarea className="block w-full rounded bg-ink-900 border p-2" maxLength={400} value={value} onChange={e=>{set(e.target.value);setDecisionKey(crypto.randomUUID());}}/></label>)}
 <button disabled={!!busy||!image||![chosen,why,process,behavior].every(v=>v.trim())} onClick={annotate}>Save decision draft</button><p className="text-sm">Review and accept each saved decision separately. Acceptance records evidence; it does not claim the agent is trained or automatically add it to every run.</p></section>}
 </main>;
}
