/**
 * lib/professional-v2-contract.ts — the ONE place the browser learns what the
 * deployed backend will accept for `professional-generation-control.v2`.
 *
 * Every number, string and ratio here is read off lib/professional-v2.fixtures.ts,
 * which is generated by PROBING the real producer at a pinned commit (see
 * scripts/regenerate-professional-v2-fixtures.mjs). Nothing is transcribed from a
 * schema or a doc, so a bound that moves in the backend moves here on the next
 * regeneration rather than quietly disagreeing with the editor that enforces it.
 *
 * WHAT THIS MODULE MUST NEVER BECOME
 *
 * A second opinion. The dashboard does not price work, does not decide which
 * providers exist, and does not decide whether Professional is available. It
 * enforces the same bounds the backend enforces so a user is refused in the
 * editor instead of after a round trip — and every authoritative figure still
 * comes back from the backend and is reconciled against what was computed here.
 * `reconcile*` failing is a REFUSAL, never a fallback to the local number.
 */

import {
  BACKEND_PIN, CAPABILITY_KEY, COMPILER_VERSION, CONTRACT_VERSION,
  CONTROL_CONTRACT_V1, CONTROL_CONTRACT_V2, DERIVED_PROMPT_SUFFIXES,
  DESKTOP_CAPABILITY_VERSION, MAX_SOURCE_PROMPT_CHARS, PROBED_BOUNDS,
  PROVIDER_CATALOG, PROVIDER_PIN, REQUEST_SUPPORTED_RATIOS,
} from './professional-v2.fixtures.ts';

export const BACKEND_CONTRACT_PIN: string = BACKEND_PIN;
export const CONTROL_V1: string = CONTROL_CONTRACT_V1;
export const CONTROL_V2: string = CONTROL_CONTRACT_V2;
export const V2_DESKTOP_CAPABILITY_VERSION: string = DESKTOP_CAPABILITY_VERSION;
export const V2_COMPILER_VERSION: string = COMPILER_VERSION;
export const V2_CONTRACT_VERSION: string = CONTRACT_VERSION;
export const V2_CAPABILITY_KEY: string = CAPABILITY_KEY;

export type JudgeMode = 'off' | 'ranked';

export const JUDGE_MODES: readonly JudgeMode[] = PROBED_BOUNDS.judgeModes as readonly JudgeMode[];
export const JUDGE_MODES_ALLOWING_REPAIR: readonly JudgeMode[] =
  PROBED_BOUNDS.judgeModesAllowingRepair as readonly JudgeMode[];

export const BOUNDS = {
  maxMoments: PROBED_BOUNDS.maxMoments,
  minVariantsPerMoment: PROBED_BOUNDS.minVariantsPerMoment,
  maxVariantsPerMoment: PROBED_BOUNDS.maxVariantsPerMoment,
  maxRepairsPerMoment: PROBED_BOUNDS.maxRepairsPerMoment,
  maxTotalTasks: PROBED_BOUNDS.maxTotalTasks,
  minDurationSeconds: PROBED_BOUNDS.minDurationSeconds,
  maxDurationSeconds: PROBED_BOUNDS.maxDurationSeconds,
  /** The REQUEST-side ceiling on the source prompt, before any suffix. */
  promptMaxChars: PROBED_BOUNDS.promptMaxChars,
} as const;

/**
 * The moment-id grammar the backend enforces. Mirrored, and asserted against the
 * producer's own accept/reject verdicts in professional-v2-contract.test.ts —
 * a drifting pattern fails a test rather than refusing ids the backend accepts.
 */
export const MOMENT_ID_PATTERN = /^[a-z0-9][a-z0-9_-]{0,39}$/;

/** Ratios the REQUEST path accepts. A strict subset of the price catalog's list. */
export const SUPPORTED_RATIOS: readonly string[] = REQUEST_SUPPORTED_RATIOS;
export const DEFAULT_RATIO: string = REQUEST_SUPPORTED_RATIOS[0];

export type ProviderCapability = {
  provider: string;
  model: string;
  pricing_version: string;
  credits_per_second: number;
  supported_ratios: readonly string[];
  min_duration_seconds: number;
  max_duration_seconds: number;
  max_prompt_chars: number;
  strengths: readonly string[];
};

/**
 * The provider identity the backend PINS server-side. The browser never names a
 * provider, model or pricing version in a request — `normalizeV2RequestMoments`
 * overwrites whatever a client sends — so this exists purely so the editor can
 * SHOW which engine the backend will use, with the strengths the catalog states.
 */
export const PINNED_PROVIDER: { provider: string; model: string; pricing_version: string } = {
  provider: PROVIDER_PIN.provider,
  model: PROVIDER_PIN.model,
  pricing_version: PROVIDER_PIN.pricing_version,
};

export const PROVIDER_CAPABILITIES: readonly ProviderCapability[] =
  PROVIDER_CATALOG as unknown as readonly ProviderCapability[];

/**
 * The catalogued capability for the pinned identity, or null. Null means the
 * dashboard has no verified rate for what the backend will run and must not
 * state one — it shows structure only and waits for the backend's own figures.
 */
export function pinnedProviderCapability(): ProviderCapability | null {
  return PROVIDER_CAPABILITIES.find((entry) => entry.provider === PINNED_PROVIDER.provider
    && entry.model === PINNED_PROVIDER.model
    && entry.pricing_version === PINNED_PROVIDER.pricing_version) ?? null;
}

/**
 * The room left for the SOURCE prompt at this moment's shape.
 *
 * Two ceilings apply and the tighter one wins: the request path's own cap on
 * what a client may send, and the provider's cap on the FINAL derived string —
 * which is longer, because variant and repair suffixes are appended after the
 * user has stopped typing. A field that only enforced the first would let a user
 * write a prompt that is refused at compile time, after they have committed to a
 * plan.
 */
export function maxSourcePromptChars(variantsRequested: number, maxRepairs: number): number {
  const byVariants = (MAX_SOURCE_PROMPT_CHARS as Record<string, Record<string, number>>)[String(variantsRequested)];
  const providerRoom = byVariants ? byVariants[String(maxRepairs)] : undefined;
  if (typeof providerRoom !== 'number') return BOUNDS.promptMaxChars;
  return Math.min(BOUNDS.promptMaxChars, providerRoom);
}

/**
 * The exact string the provider receives for one task, rebuilt from the pinned
 * suffix table. Used to BIND a returned proposal to the words the user typed: a
 * well-formed proposal carrying someone else's intent is still the wrong spend.
 */
export function derivedCandidatePrompt(
  sourcePrompt: string, candidateOrdinal: number, variantsRequested: number,
): string | null {
  const table = (DERIVED_PROMPT_SUFFIXES.candidate as Record<string, Record<string, string>>)[String(variantsRequested)];
  const suffix = table ? table[String(candidateOrdinal)] : undefined;
  return typeof suffix === 'string' ? `${sourcePrompt}${suffix}` : null;
}

export function derivedRepairPrompt(sourcePrompt: string): string {
  return `${sourcePrompt}${DERIVED_PROMPT_SUFFIXES.repair}`;
}

/**
 * Duration in whole seconds, derived the way the backend derives it: millisecond
 * timestamps, then CEIL. A 2.5-second window is a 3-second task and is priced as
 * one — showing 2.5 would understate the ceiling the user is authorizing.
 */
export function durationSecondsFor(startMs: number, endMs: number): number {
  return Math.ceil((endMs - startMs) / 1000);
}

/** Seconds → the integer milliseconds the request carries. */
export function toMs(seconds: number): number {
  return Math.round(seconds * 1000);
}

/**
 * Credits for ONE task at this duration and ratio, from the catalogued rate.
 * Null when the pinned combination is not catalogued, the ratio is unsupported,
 * or the duration is outside the provider's bounds — the same three refusals the
 * backend makes, and for the same reason: a rate guessed from a neighbouring
 * entry is a confidently wrong ceiling.
 */
export function creditsPerTask(durationSeconds: number, ratio: string): number | null {
  const capability = pinnedProviderCapability();
  if (!capability) return null;
  if (!Number.isSafeInteger(durationSeconds)) return null;
  if (durationSeconds < capability.min_duration_seconds || durationSeconds > capability.max_duration_seconds) return null;
  if (!capability.supported_ratios.includes(ratio)) return null;
  return capability.credits_per_second * durationSeconds;
}
