// node --test lib/professional-v2-contract.test.ts
//
// The contract mirror, checked against the PRODUCER'S OWN VERDICTS.
//
// Every fixture consulted here was generated by asking the deployed backend
// compiler what it accepts (scripts/regenerate-professional-v2-fixtures.mjs). So
// these are not "does the constant equal the number I typed" tests — they are
// "does this build refuse exactly what the backend refuses, and accept exactly
// what it accepts". A drifting bound fails here rather than in production, where
// it would refuse plans the backend would have compiled, or wave through plans
// it will not.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  BOUNDS, CONTROL_V1, CONTROL_V2, JUDGE_MODES, JUDGE_MODES_ALLOWING_REPAIR,
  MOMENT_ID_PATTERN, PINNED_PROVIDER, SUPPORTED_RATIOS,
  creditsPerTask, derivedCandidatePrompt, derivedRepairPrompt, durationSecondsFor,
  maxSourcePromptChars, pinnedProviderCapability, toMs,
} from './professional-v2-contract.ts';
import {
  MOMENT_ID_VERDICTS, PROBED_BOUNDS, V2_PREVIEW_AVAILABLE, V2_PREVIEW_JUDGE_OFF,
  V2_PREVIEW_MULTI, PROVIDER_PIN,
} from './professional-v2.fixtures.ts';

test('the moment-id pattern reaches the producer’s verdict on every probed id', () => {
  for (const { id, accepted } of MOMENT_ID_VERDICTS) {
    assert.equal(
      MOMENT_ID_PATTERN.test(id), accepted,
      `moment id ${JSON.stringify(id)}: mirror says ${MOMENT_ID_PATTERN.test(id)}, backend says ${accepted}`,
    );
  }
});

test('the bounds are the probed bounds, and Professional is 1–4 variants with at most one reserve', () => {
  assert.equal(BOUNDS.maxMoments, PROBED_BOUNDS.maxMoments);
  assert.equal(BOUNDS.minVariantsPerMoment, 1);
  assert.equal(BOUNDS.maxVariantsPerMoment, 4);
  assert.equal(BOUNDS.maxRepairsPerMoment, 1);
  assert.equal(BOUNDS.maxTotalTasks, 40);
  assert.equal(BOUNDS.minDurationSeconds, 2);
  assert.equal(BOUNDS.maxDurationSeconds, 10);
  assert.equal(BOUNDS.promptMaxChars, 700);
  assert.deepEqual([...JUDGE_MODES], ['off', 'ranked']);
  // Repair under judge-off is refused by the producer, so the mirror must not
  // list `off` as a mode a reserve may accompany.
  assert.deepEqual([...JUDGE_MODES_ALLOWING_REPAIR], ['ranked']);
});

test('the discriminator literals are distinct and exact', () => {
  assert.equal(CONTROL_V2, 'professional-generation-control.v2');
  assert.equal(CONTROL_V1, 'professional-generation-control.v1');
  assert.notEqual(CONTROL_V1, CONTROL_V2);
});

test('only ratios the request path accepts are offered', () => {
  assert.deepEqual([...SUPPORTED_RATIOS], ['720:1280']);
  // The price catalog lists a landscape ratio the request path refuses. Offering
  // it would let a user build a plan the compiler rejects.
  const capability = pinnedProviderCapability();
  assert.ok(capability);
  assert.ok(capability.supported_ratios.length > SUPPORTED_RATIOS.length);
});

test('the provider identity is the backend’s pin, and carries no credential', () => {
  assert.equal(PINNED_PROVIDER.provider, PROVIDER_PIN.provider);
  assert.equal(PINNED_PROVIDER.model, PROVIDER_PIN.model);
  assert.equal(PINNED_PROVIDER.pricing_version, PROVIDER_PIN.pricing_version);
  assert.equal(JSON.stringify(PINNED_PROVIDER).includes('key'), false);
});

test('duration is ceiled from the window, exactly as the backend derives it', () => {
  assert.equal(durationSecondsFor(0, 3000), 3);
  assert.equal(durationSecondsFor(0, 2500), 3);
  assert.equal(durationSecondsFor(1500, 4000), 3);
  assert.equal(toMs(3.25), 3250);
});

test('credits are derived from the catalogued rate, and refused outside its bounds', () => {
  const capability = pinnedProviderCapability();
  assert.ok(capability);
  assert.equal(creditsPerTask(3, '720:1280'), capability.credits_per_second * 3);
  // Outside the provider's duration bounds, or on an uncatalogued ratio, there is
  // no verified rate — and a rate borrowed from a neighbouring entry would be a
  // confidently wrong ceiling.
  assert.equal(creditsPerTask(1, '720:1280'), null);
  assert.equal(creditsPerTask(11, '720:1280'), null);
  assert.equal(creditsPerTask(3, '1920:1080'), null);
});

test('the compiled credits in a real proposal match the local derivation', () => {
  for (const moment of V2_PREVIEW_MULTI.proposal.professional_control.moments) {
    assert.equal(
      creditsPerTask(moment.duration_seconds, moment.ratio), moment.credits_per_task,
      `moment ${moment.moment_id}`,
    );
  }
});

test('the prompt ceiling accounts for the suffix the provider actually receives', () => {
  // One take, no reserve: nothing is appended, so the request cap is the only
  // limit. More takes append a longer instruction, and the room shrinks.
  assert.equal(maxSourcePromptChars(1, 0), BOUNDS.promptMaxChars);
  assert.ok(maxSourcePromptChars(4, 1) <= maxSourcePromptChars(1, 0));
  // The room is never wider than the request cap, whatever the provider allows.
  for (let variants = 1; variants <= BOUNDS.maxVariantsPerMoment; variants += 1) {
    for (let repairs = 0; repairs <= BOUNDS.maxRepairsPerMoment; repairs += 1) {
      assert.ok(maxSourcePromptChars(variants, repairs) <= BOUNDS.promptMaxChars);
    }
  }
});

test('derived prompts rebuild exactly what the compiler emitted', () => {
  for (const fixture of [V2_PREVIEW_AVAILABLE, V2_PREVIEW_JUDGE_OFF, V2_PREVIEW_MULTI]) {
    const graph = fixture.proposal.professional_control;
    const tasks = new Map(graph.authorization_tasks.map((t) => [t.task_id, t]));
    for (const moment of graph.moments) {
      for (const taskId of moment.candidate_task_ids) {
        const task = tasks.get(taskId)!;
        assert.equal(
          derivedCandidatePrompt(moment.prompt, task.candidate_ordinal as number, moment.variants_requested),
          task.prompt_text, `${taskId} derived prompt`,
        );
      }
      for (const taskId of moment.repair_task_ids) {
        assert.equal(derivedRepairPrompt(moment.prompt), tasks.get(taskId)!.prompt_text, `${taskId} repair prompt`);
      }
    }
  }
});

test('a single-variant moment sends the prompt verbatim', () => {
  // The compiler appends nothing when there is only one take. A mirror that
  // always appended would fail to bind a judge-off plan to what the user typed.
  assert.equal(derivedCandidatePrompt('a bridge at dawn', 1, 1), 'a bridge at dawn');
  assert.equal(derivedCandidatePrompt('a bridge at dawn', 2, 1), null);
});
